"""Update fields in Message model

Revision ID: 0a90c4d14830
Revises: a1c4932e1d85
Create Date: 2023-06-01 11:24:01.801459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a90c4d14830'
down_revision = 'a1c4932e1d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('room')

    # ### end Alembic commands ###
